---
# Service account to be used for the pod
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-lambda-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with $annotations := .Values.serviceAccount.metadata.annotations }}
  annotations:
    {{- $annotations | toYaml | nindent 4 }}
  {{- end }}
  {{- with $labels := .Values.serviceAccount.metadata.labels }}
  labels:
    {{- $labels | toYaml | nindent 4 }}
  {{- end }}
