name: changes
description: determine changes to repository
outputs:
  changes:
    description: "changes to files in the repositories"
    value: ${{ steps.changes.outputs }}
runs:
  using: "composite"
  steps:
    # Determine changes
    - name: determine changes
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          golang:
            - '**/*.go'
            - '**/testdata/**'
            - 'go.mod'
            - 'go.sum'
            - '.golangci.yaml'
          helm:
            - 'charts/**'
            - '.yamllint'
          docker:
            - 'Dockerfile'
            - '.dockerignore'
            - '.hadolint.yaml'
            - 'buildinfo/*.sh'
