on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: false
        default: ""
      push:
        type: boolean
        required: false
        default: true
      platforms:
        required: false
        type: string
        default: ""
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build docker image
        id: docker-build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: ${{ ! inputs.push }}
          push: ${{ inputs.push }}
          platforms: ${{ inputs.platforms }}
          build-args: |
            VERSION=${{ github.ref_name }}
            COMMIT_SHA=${{ github.sha }}
          tags: ${{ inputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

