on:
  workflow_call:
    inputs:
      platforms:
        required: false
        type: string
        default: ""
jobs:
  setup-docker:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: "${{ inputs.platforms }}"
    steps:
      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ inputs.platforms }}

