on:
  workflow_call:
    inputs: {}
jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v4
        if: steps.changes.outputs.golang == 'true'
        with:
          go-version: "1.20"
      - id: go-cache-paths
        if: steps.changes.outputs.golang == 'true'
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      - name: setup go build-cache
        if: steps.changes.outputs.golang == 'true'
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
      - name: setup go-mod-cache
        if: steps.changes.outputs.golang == 'true'
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}