name: "verify"
on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]
env:
  CHANGE_FILTERS: |
    golang:
      - '**/*.go'
      - '**/testdata/**'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yaml'
    helm:
      - 'charts/**'
      - '.yamllint'
    docker:
      - 'Dockerfile'
      - '.dockerignore'
      - '.hadolint.yaml'
      - 'buildinfo/*.sh'
jobs:
  golang:
    uses: ./.github/workflows/verify-go.yaml
  docker:
    uses: ./.github/workflows/verify-docker.yaml
  helm:
    uses: ./.github/workflows/verify-helm.yaml
