name: "verify"
on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]
jobs:
  golang:
    uses: ./.github/workflows/verify-go.yaml
  docker:
    uses: ./.github/workflows/verify-docker.yaml
  helm:
    uses: ./.github.com/workflows/verify-helm.yaml
