on:
  workflow_call:
    inputs: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    # Run hadolint
    steps:
      # Checkout
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Determine changes
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: ${{ env.CHANGE_FILTERS }}
      - uses: hadolint/hadolint-action@v3.1.0
        if: steps.changes.outputs.docker == 'true' || steps.changes.outputs.golang == 'true'
        with:
          dockerfile: Dockerfile
  test:
    runs-on: ubuntu-latest
    # Build docker image
    steps:
      # Checkout
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Determine changes
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: ${{ env.CHANGE_FILTERS }}
      - uses: ./.github/actions/docker-setup
        if: steps.changes.outputs.docker == 'true' || steps.changes.outputs.golang == 'true' || steps.changes.outputs.helm == 'true'
      - uses: ./.github/actions/docker-build
        if: steps.changes.outputs.docker == 'true' || steps.changes.outputs.golang == 'true' || steps.changes.outputs.helm == 'true'
        with:
          tags: aws-lambda-server:${{ github.sha }}
          push: false
