on:
  workflow_call:
    inputs: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Determine changes
      - uses: ./.github/actions/changes
        id: changes
      - uses: ./.github/actions/setup-helm
      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
        if: steps.changes.outputs.helm == 'true'
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Determine changes
      - uses: ./.github/actions/changes
        id: changes
      - uses: ./.github/actions/helm-setup
      # Create a KiND cluster
      - name: Create kind cluster
        if: steps.changes.outputs.helm == 'true'
        uses: helm/kind-action@v1.4.0
      # Run the installation for the chart, loading the temporary docker image and using it for the deployment
      - name: Run chart-testing (install)
        if: steps.changes.outputs.docker == 'true' || steps.changes.outputs.golang == 'true' || steps.changes.outputs.helm == 'true'
        timeout-minutes: 2
        run: |
          kind load docker-image aws-lambda-server:${{ github.sha }} --name chart-testing
          ct install\
           --target-branch ${{ github.event.repository.default_branch }}\
           --helm-extra-set-args "
          --set-string=deployment.image.tag=${{ github.sha }} \
          --set-string=deployment.image.repository=aws-lambda-server"\
           --debug

